### ISSUE TITLE
Desenvolver fluxograma de funcionamento do sistema

### ISSUE THREAD

**Issue by iliscio** [iliscio/es1s20-grupo03#11]
Desenvolver e documentar lógica de funcionamento do sistema.

**Comment by E-Rombi** [comment]
Funcionamento do Sistema

Perspectivas serão carregadas de acordo com o login realizado na aplicação.

 i . Prestador de Serviço
    * Realizar o Cadastro de suas informações, tais como informações pessoais e também de seu(s) 
       veículos de trabalho.
    * Visualizar histórico de contratos realizados,
    * Visualizar contratos pendentes e/ou em análise.
    * Realizar o download de um contrato.
    * Realizar o upload de um contrato.
ii . Contratante
    * Realizar o Cadastro de suas informações, tais como informações pessoais.
    * Visualizar histórico de contratos realizados,
    * Visualizar contratos pendentes e/ou em análise.
    * Realizar o download de um contrato.
    * Realizar o upload de um contrato.
    * Entrar em contato com o prestador de serviço diretamente pela aplicação (via e-mail).
