### ISSUE TITLE
Desenvolver artes do sistema

### ISSUE THREAD

**Issue by iliscio** [iliscio/es1s20-grupo03#12]
Desenvolver imagens e layouts utilizados dentro do sistema, a fim de caracterizar o sistema e torná-lo mais agradável aos usuários.

**Comment by enricogp** [comment]
Cores dos botões foram alteradas para dar uma melhor visibilidade

**Comment by enricogp** [comment]
ícone do calendário adicionado

**Comment by enricogp** [comment]
![Sem título3](https://user-images.githubusercontent.com/57647198/84094021-26f46a80-a9d2-11ea-89dc-45273f3f86a7.png)

Efeito "zebra" adicionado

**Comment by enricogp** [comment]
Reorganização do popup "carregar contrato"
